"""Generate docs/data_samples.md: column list + 5-row sample of each raw source.

Usage (from the repo root, after downloading the raw files into data/raw/):
    uv run python scripts/make_data_samples.py data/raw/foia-7a-fy2010-fy2019.csv data/raw/foia-7a-fy2020-present.csv data/raw/laucnty24.xlsx

Borrower name/street columns are dropped so no personal details are committed.
"""
import sys
from pathlib import Path

import pandas as pd

OUT = Path("docs/data_samples.md")
PII_HINTS = ("borrname", "borrstreet", "borrower name", "street")


def load(path: Path) -> pd.DataFrame:
    if path.suffix.lower() in (".xlsx", ".xls"):
        return pd.read_excel(path, nrows=200)
    return pd.read_csv(path, nrows=200, low_memory=False, encoding_errors="replace")


def main(paths):
    parts = ["# Data Source Samples\n",
             "Auto-generated by `scripts/make_data_samples.py`. "
             "First 5 rows of each raw file; borrower name/street columns removed.\n"]
    for p in map(Path, paths):
        df = load(p)
        df = df[[c for c in df.columns if not any(h in str(c).lower() for h in PII_HINTS)]]
        parts.append(f"\n## `{p.name}`\n")
        parts.append(f"Columns ({len(df.columns)}): " + ", ".join(f"`{c}`" for c in df.columns) + "\n")
        parts.append(df.head(5).to_markdown(index=False) + "\n")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(sys.argv[1:])
